# Generated by Django 3.0.5 on 2021-01-15 21:24

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CalculationInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ef', models.FloatField()),
                ('cu', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='NavigationInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scope', models.CharField(max_length=150)),
                ('level1', models.CharField(max_length=150)),
                ('level2', models.CharField(max_length=150)),
                ('level3', models.CharField(max_length=150)),
                ('level4', models.CharField(max_length=150)),
                ('level5', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='OtherInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_update', models.DateTimeField(default=django.utils.timezone.now)),
                ('preference', models.IntegerField()),
                ('source', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='FlatfileEntry',
            fields=[
                ('ref_num', models.IntegerField(default=0, primary_key=True, serialize=False)),
                ('calculation_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.CalculationInfo')),
                ('navigation_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.NavigationInfo')),
                ('other_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.OtherInfo')),
            ],
        ),
    ]
