# Generated by Django 3.0.5 on 2021-02-24 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='navigationinfo',
            name='level2',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='navigationinfo',
            name='level3',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='navigationinfo',
            name='level4',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='navigationinfo',
            name='level5',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
