# Generated by Django 3.0.5 on 2021-01-14 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flatfileentry',
            name='flag',
        ),
    ]
