# Generated by Django 3.0.5 on 2021-03-03 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20210303_1642'),
    ]

    operations = [
        migrations.AlterField(
            model_name='navigationinfo',
            name='level1',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='navigationinfo',
            name='level2',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='navigationinfo',
            name='level3',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='navigationinfo',
            name='level4',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='navigationinfo',
            name='level5',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
